"""alter_embedding_to_2048_and_recreate_hnsw

Revision ID: 195ca4715531
Revises: a2c718e53341
Create Date: 2026-07-20 17:48:34.635198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '195ca4715531'
down_revision: Union[str, Sequence[str], None] = 'a2c718e53341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Remove existing chunks before altering the vector dimension.
    op.execute(text("DELETE FROM document_chunks"))
    op.execute(text("DROP INDEX IF EXISTS ix_document_chunks_embedding_hnsw"))
    op.execute(text("DROP INDEX IF EXISTS ix_document_chunks_embedding_ivfflat"))
    op.execute(text("DROP INDEX IF EXISTS ix_document_chunks_embedding_hnsw_halfvec"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=Vector(dim=1536),
               type_=Vector(dim=2048),
               existing_nullable=True)
    # ### end Alembic commands ###

    # pgvector 0.8.x limits HNSW/IVFFlat on vector(n) to n <= 2000.
    # Workaround: functional index casting to halfvec, which accepts 2048 dims.
    op.execute(
        text(
            "CREATE INDEX ix_document_chunks_embedding_hnsw_halfvec "
            "ON document_chunks USING hnsw "
            "(CAST(embedding AS halfvec(2048)) halfvec_cosine_ops)"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(text("DELETE FROM document_chunks"))
    op.execute(text("DROP INDEX IF EXISTS ix_document_chunks_embedding_hnsw"))
    op.execute(text("DROP INDEX IF EXISTS ix_document_chunks_embedding_ivfflat"))
    op.execute(text("DROP INDEX IF EXISTS ix_document_chunks_embedding_hnsw_halfvec"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=Vector(dim=2048),
               type_=Vector(dim=1536),
               existing_nullable=True)
    # ### end Alembic commands ###
