"""add_uploaded_documents

Revision ID: a2c718e53341
Revises: 3c81ca3fef26
Create Date: 2026-07-20 12:31:07.899372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2c718e53341'
down_revision: Union[str, Sequence[str], None] = '3c81ca3fef26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('docling_document', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False, server_default=sa.text("'local-upload'")),
    sa.Column('converted_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False, server_default=sa.text("'converted'")),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('table_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('units', sa.String(length=255), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('table_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('source_html_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'table_index', name='uq_document_tables_document_table')
    )
    op.create_index('ix_document_tables_document_id', 'document_tables', ['document_id'], unique=False)
    op.alter_column('document_chunks', 'section',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_document_chunks_chunk_metadata_gin'), table_name='document_chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_document_chunks_embedding_hnsw'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_document_chunks_search_vector_gin'), table_name='document_chunks', postgresql_using='gin')
    op.drop_column('document_chunks', 'search_vector')
    op.alter_column('message_citations', 'section',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###

    op.execute(
        "ALTER TABLE uploaded_documents ENABLE ROW LEVEL SECURITY"
    )
    op.execute(
        """
        CREATE POLICY uploaded_documents_select_authenticated
        ON uploaded_documents
        FOR SELECT
        TO authenticated
        USING (true)
        """
    )
    op.execute(
        """
        CREATE POLICY uploaded_documents_insert_authenticated
        ON uploaded_documents
        FOR INSERT
        TO authenticated
        WITH CHECK (true)
        """
    )
    op.execute(
        """
        CREATE POLICY uploaded_documents_update_own
        ON uploaded_documents
        FOR UPDATE
        TO authenticated
        USING (true)
        WITH CHECK (true)
        """
    )
    op.execute(
        """
        CREATE POLICY uploaded_documents_delete_own
        ON uploaded_documents
        FOR DELETE
        TO authenticated
        USING (true)
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_citations', 'section',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.add_column('document_chunks', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, text)", persisted=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_document_chunks_search_vector_gin'), 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_chunks_embedding_hnsw'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_document_chunks_chunk_metadata_gin'), 'document_chunks', ['chunk_metadata'], unique=False, postgresql_using='gin')
    op.alter_column('document_chunks', 'section',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index('ix_document_tables_document_id', table_name='document_tables')
    op.drop_table('document_tables')
    op.drop_table('uploaded_documents')
    # ### end Alembic commands ###
